<h1> A Python Web Scraper that gets information of Stocks on the S&P 500

In [9]:
import bs4 as bs
import requests
import pandas as pd

In [31]:
req = requests.get('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
scraper = bs.BeautifulSoup(req.text,'lxml')
data_table = scraper.find('table',{'class':'wikitable sortable'})
# print(data_table)
#print(data_table.findAll('tr')[1:])#Gets the rows except the first one

stocks = []
securities = []
industries = []
sub_industries = []
locations = [] 

for row in data_table.findAll('tr')[1:]:
    stock = row.findAll('td')[0].text
    security =row.findAll('td')[1].text
    industry = row.findAll('td')[3].text
    sub_industry = row.findAll('td')[4].text
    location = row.findAll('td')[5].text
    
    stocks.append(stock)
    securities.append(security)
    industries.append(industry)
    sub_industries.append(sub_industry)
    locations.append(location)

<h1> Extracted Data

In [32]:
stocks = list(map(str.strip,stocks))
securities = list(map(str.strip,securities))
industries = list(map(str.strip,industries))
sub_industries = list(map(str.strip,sub_industries))
locations = list(map(str.strip,locations))

#print(stocks)

stocks_data = pd.DataFrame(stocks, columns=['Stock Name'])
security_data =pd.DataFrame(securities,columns=['Security'])
industries_data =pd.DataFrame(industries,columns=['Sector'])
sub_industries_data = pd.DataFrame(sub_industries,columns=['Industry'])
locations_data= pd.DataFrame(locations, columns=['Locations'])


df = pd.concat([stocks_data,security_data,industries_data,sub_industries_data,locations_data],axis=1)
df

# Filtering
# df_new =df.loc[df['Sector']=='Health Care']
# print(df_new['Stock Name'].tolist())

,Stock Name,Security,Sector,Industry,Locations
0,MMM,3M Company,Industrials,Industrial Conglomerates,"St. Paul, Minnesota"
1,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois"
2,ABBV,AbbVie Inc.,Health Care,Pharmaceuticals,"North Chicago, Illinois"
3,ABMD,ABIOMED Inc,Health Care,Health Care Equipment,"Danvers, Massachusetts"
4,ACN,Accenture plc,Information Technology,IT Consulting & Other Services,"Dublin, Ireland"
...,...,...,...,...,...
500,YUM,Yum! Brands Inc,Consumer Discretionary,Restaurants,"Louisville, Kentucky"
501,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois"
502,ZBH,Zimmer Biomet Holdings,Health Care,Health Care Equipment,"Warsaw, Indiana"
503,ZION,Zions Bancorp,Financials,Regional Banks,"Salt Lake City, Utah"
504,ZTS,Zoetis,Health Care,Pharmaceuticals,"Florham Park, New Jersey"